name: PR automations
on:
  pull_request:
    branches:
      - main

jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ec2-github-runner-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: npm install
      - name: Run linter
        run: npm run lint

  update-dist:
    name: Update dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Package
        run: npm run package
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Update dist" || echo "No changes to commit"
          git push origin ${{ github.ref }}
